spring.application.name=ArenaMix
# Puerto donde arrancará tu servidor local
server.port=8080

# Conexión a la base de datos de AWS
spring.datasource.url=jdbc:mysql://basededatostfg.c723sjtt6jy2.us-east-1.rds.amazonaws.com:3306/basedatostfg
spring.datasource.username=admin_tfg
spring.datasource.password=ChuckNorris2025

# Configuración de JPA (Hibernate)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
